### ISSUE TITLE
Drop in not working - crash on app startup - image not found - 5.2.0

### ISSUE THREAD

**Issue by zauberware** [NAXAM/braintreedropin-ios-binding#1]
When we integrate the nuget package and try to use it, the app crashs directly at startup with the error message "image not found".
Maybe the "Mach-O Type" under "Build Settings" was set to "Dynamic Library" instead of "Static Library"?

**Comment by tuyen-vuduc** [comment]
Commit 10986d2 fixed your issue. It's a mistake when too many bindings were created at once.

**Comment by marcus-franzen** [comment]
I think there is still a problem. We can not see the paypal button, although we have tried a lot of different settings.

Could it be that the PayPalUtils are not correctly linked?

dyld: Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils
  Referenced from: /private/var/containers/Bundle/Application/54644A34-8E25-4794-8CC0-8ABD9F2B8709/myCoffee.iOS.app/Frameworks/PayPalOneTouch.framework/PayPalOneTouch
  Reason: image not found

**Comment by tuyen-vuduc** [comment]
Have you added PaypalUtils nuget to your iOS app project?

**Comment by marcus-franzen** [comment]
![bildschirmfoto 2017-07-12 um 10 32 49](https://user-images.githubusercontent.com/30052863/28108927-84c76ce6-66ed-11e7-9773-e32b951b372a.png)

**Comment by tuyen-vuduc** [comment]
Hey,

If you don't mind, I am happy to teamviewer to see the details with you.

My Skype is tuyen.vuduc0902@gmail.com

Regards.

**Comment by tomahutbui** [comment]
> I think there is still a problem. We can not see the paypal button, although we have tried a lot of different settings.
> 
> Could it be that the PayPalUtils are not correctly linked?
> 
> dyld: Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils
> Referenced from: /private/var/containers/Bundle/Application/54644A34-8E25-4794-8CC0-8ABD9F2B8709/myCoffee.iOS.app/Frameworks/PayPalOneTouch.framework/PayPalOneTouch
> Reason: image not found

replace libPayPalDataCollector.a file instead of PayPalDataCollector.Framework. Rebuild project binding and use it.

@tuyen-vuduc : bạn đổi reference native thay vì framework thì dùng static lib trong project ios base của braintree là fix đc cái này. Mình cũng bị, thay vào build lại là chạy ok

**Comment by tuyen-vuduc** [comment]
@tomahutbui 

Thank you very much for your point.

It's about the linker. We could force referencing a type in PayPalUtils package, it will work.
